apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../default
images:
- name: r.deso.tech/dockerhub/kubeflownotebookswg/notebook-controller
  newName: r.deso.tech/dockerhub/kubeflownotebookswg/notebook-controller
  newTag: v1.8.0-rc.0
