---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  # Namespace.
  - ../../components/namespace/
  # Katib controller.
  - ../../components/controller/
  # Katib CRDs.
  - ../../components/crd/
  # Katib DB manager.
  - ../../components/db-manager/
  # Katib DB mysql.
  - ../../components/mysql/
  # Katib UI.
  - ../../components/ui/
  # Katib webhooks.
  - ../../components/webhook/
images:
  - name: r.deso.tech/dockerhub/kubeflowkatib/katib-controller
    newName: r.deso.tech/dockerhub/kubeflowkatib/katib-controller
    newTag: v0.16.0-rc.1
  - name: r.deso.tech/dockerhub/kubeflowkatib/katib-db-manager
    newName: r.deso.tech/dockerhub/kubeflowkatib/katib-db-manager
    newTag: v0.16.0-rc.1
  - name: r.deso.tech/dockerhub/kubeflowkatib/katib-ui
    newName: r.deso.tech/dockerhub/kubeflowkatib/katib-ui
    newTag: v0.16.0-rc.1
configMapGenerator:
  - name: katib-config
    behavior: create
    files:
      - katib-config.yaml
    options:
      disableNameSuffixHash: true
# Secret for webhooks certs.
secretGenerator:
  - name: katib-webhook-cert
    options:
      disableNameSuffixHash: true
